# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: WeeShop
author: Cavas Kent
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# root: /

# Writing
relative_link: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ../node_modules/hexo-theme-doc

theme_config:
  favicon: images/bitbug_favicon.ico
  support:
    link_url: 'https://www.catwork.cn'
    text: 'WeeShop 及其文档的版权属于'
    link_text: '© 猫须科技'
    navigation: false
    navigation_label: '© 猫须科技'

ignore:
  # development only: ignore sub node_modules when `npm link hexo-theme-doc`
  - '**/node_modules/**/*node_modules'
deploy:
  - type: git
    repo: git@github.com:weeshop/documentation.git
    branch: master

marked:
  gfm: true
  pedantic: false
  breaks: false
  smartLists: true
  smartypants: true
  modifyAnchors: ''
  autolink: true
  sanitizeUrl: false
  headerIds: true
  prependRoot: false
  external_link:
    enable: false
    exclude: []
    nofollow: false